import {
  Geist,
  Geist_Mono,
  Montserrat,
  Montserrat_Alternates,
  Oxanium,
  Poppins,
  Roboto,
} from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation";
import Footer from "./components/Footer";

const textFont = Montserrat({
  variable: "--font-text",
  subsets: ["latin"],
});

const headingFont = Oxanium({
  variable: "--font-heading",
  weight: ["700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${textFont.className} ${headingFont.variable} bg-bg-primary text-text-primary antialiased`}
      >
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
